import { IGallery } from './Gallery';

export const gallery: IGallery[] = [
  {
    id: 1,
    imagePath: '/assets/img/oldBuildings/old-buildings-1.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 2,
    imagePath: '/assets/img/oldBuildings/old-buildings-2.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 3,
    imagePath: '/assets/img/oldBuildings/old-buildings-3.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 4,
    imagePath: '/assets/img/oldBuildings/old-buildings-4.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 5,
    imagePath: '/assets/img/oldBuildings/old-buildings-5.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 6,
    imagePath: '/assets/img/oldBuildings/old-buildings-6.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 7,
    imagePath: '/assets/img/oldBuildings/old-buildings-7.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 8,
    imagePath: '/assets/img/oldBuildings/old-buildings-8.jpg',
    imageAlt: 'old-builing-8',
    gallery: 'oldBuildings',
  },
  {
    id: 9,
    imagePath: '/assets/img/oldBuildings/old-buildings-9.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 10,
    imagePath: '/assets/img/oldBuildings/old-buildings-10.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 11,
    imagePath: '/assets/img/oldBuildings/old-buildings-11.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 12,
    imagePath: '/assets/img/oldBuildings/old-buildings-12.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 13,
    imagePath: '/assets/img/oldBuildings/old-buildings-13.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 14,
    imagePath: '/assets/img/oldBuildings/old-buildings-14.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 15,
    imagePath: '/assets/img/oldBuildings/old-buildings-15.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 16,
    imagePath: '/assets/img/oldBuildings/old-buildings-16.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 17,
    imagePath: '/assets/img/oldBuildings/old-buildings-17.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 18,
    imagePath: '/assets/img/oldBuildings/old-buildings-18.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 19,
    imagePath: '/assets/img/oldBuildings/old-buildings-19.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 20,
    imagePath: '/assets/img/oldBuildings/old-buildings-20.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 21,
    imagePath: '/assets/img/oldBuildings/old-buildings-21.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 22,
    imagePath: '/assets/img/oldBuildings/old-buildings-22.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 23,
    imagePath: '/assets/img/oldBuildings/old-buildings-23.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 24,
    imagePath: '/assets/img/oldBuildings/old-buildings-24.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 25,
    imagePath: '/assets/img/oldBuildings/old-buildings-25.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 26,
    imagePath: '/assets/img/oldBuildings/old-buildings-26.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 27,
    imagePath: '/assets/img/oldBuildings/old-buildings-27.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 28,
    imagePath: '/assets/img/oldBuildings/old-buildings-28.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 29,
    imagePath: '/assets/img/oldBuildings/old-buildings-29.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 30,
    imagePath: '/assets/img/oldBuildings/old-buildings-30.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 31,
    imagePath: '/assets/img/oldBuildings/old-buildings-31.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 32,
    imagePath: '/assets/img/oldBuildings/old-buildings-32.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 33,
    imagePath: '/assets/img/oldBuildings/old-buildings-33.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 34,
    imagePath: '/assets/img/oldBuildings/old-buildings-34.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 35,
    imagePath: '/assets/img/oldBuildings/old-buildings-35.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 36,
    imagePath: '/assets/img/oldBuildings/old-buildings-36.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 37,
    imagePath: '/assets/img/oldBuildings/old-buildings-37.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 38,
    imagePath: '/assets/img/oldBuildings/old-buildings-38.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 39,
    imagePath: '/assets/img/oldBuildings/old-buildings-39.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 40,
    imagePath: '/assets/img/oldBuildings/old-buildings-40.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
];
