import { IGallery } from '../gallery/Gallery';

export const gallery: IGallery[] = [
  {
    id: 1,
    imagePath: '/assets/img/oldBuildings/old-buildings-1.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 2,
    imagePath: '/assets/img/oldBuildings/old-buildings-2.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 3,
    imagePath: '/assets/img/oldBuildings/old-buildings-3.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 4,
    imagePath: '/assets/img/oldBuildings/old-buildings-4.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 5,
    imagePath: '/assets/img/oldBuildings/old-buildings-5.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 6,
    imagePath: '/assets/img/oldBuildings/old-buildings-6.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 7,
    imagePath: '/assets/img/oldBuildings/old-buildings-7.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 8,
    imagePath: '/assets/img/oldBuildings/old-buildings-8.jpg',
    imageAlt: 'old-builing-8',
    gallery: 'oldBuildings',
  },
  {
    id: 9,
    imagePath: '/assets/img/oldBuildings/old-buildings-9.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 10,
    imagePath: '/assets/img/oldBuildings/old-buildings-10.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 11,
    imagePath: '/assets/img/oldBuildings/old-buildings-11.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 12,
    imagePath: '/assets/img/oldBuildings/old-buildings-12.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 13,
    imagePath: '/assets/img/oldBuildings/old-buildings-13.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 14,
    imagePath: '/assets/img/oldBuildings/old-buildings-14.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 15,
    imagePath: '/assets/img/oldBuildings/old-buildings-15.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 16,
    imagePath: '/assets/img/oldBuildings/old-buildings-16.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 17,
    imagePath: '/assets/img/oldBuildings/old-buildings-17.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 18,
    imagePath: '/assets/img/oldBuildings/old-buildings-18.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 19,
    imagePath: '/assets/img/oldBuildings/old-buildings-19.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 20,
    imagePath: '/assets/img/oldBuildings/old-buildings-20.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 21,
    imagePath: '/assets/img/oldBuildings/old-buildings-21.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 22,
    imagePath: '/assets/img/oldBuildings/old-buildings-22.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 23,
    imagePath: '/assets/img/oldBuildings/old-buildings-23.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 24,
    imagePath: '/assets/img/oldBuildings/old-buildings-24.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 25,
    imagePath: '/assets/img/oldBuildings/old-buildings-25.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 26,
    imagePath: '/assets/img/oldBuildings/old-buildings-26.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 27,
    imagePath: '/assets/img/oldBuildings/old-buildings-27.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 28,
    imagePath: '/assets/img/oldBuildings/old-buildings-28.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 29,
    imagePath: '/assets/img/oldBuildings/old-buildings-29.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 30,
    imagePath: '/assets/img/oldBuildings/old-buildings-30.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 31,
    imagePath: '/assets/img/oldBuildings/old-buildings-31.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 32,
    imagePath: '/assets/img/oldBuildings/old-buildings-32.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 33,
    imagePath: '/assets/img/oldBuildings/old-buildings-33.jpg',
    imageAlt: 'old-builing-6',
    gallery: 'oldBuildings',
  },
  {
    id: 34,
    imagePath: '/assets/img/oldBuildings/old-buildings-34.jpg',
    imageAlt: 'old-builing-7',
    gallery: 'oldBuildings',
  },
  {
    id: 35,
    imagePath: '/assets/img/oldBuildings/old-buildings-35.jpg',
    imageAlt: 'old-builing-1',
    gallery: 'oldBuildings',
  },
  {
    id: 36,
    imagePath: '/assets/img/oldBuildings/old-buildings-36.jpg',
    imageAlt: 'old-builing-2',
    gallery: 'oldBuildings',
  },
  {
    id: 37,
    imagePath: '/assets/img/oldBuildings/old-buildings-37.jpg',
    imageAlt: 'old-builing-3',
    gallery: 'oldBuildings',
  },
  {
    id: 38,
    imagePath: '/assets/img/oldBuildings/old-buildings-38.jpg',
    imageAlt: 'old-builing-4',
    gallery: 'oldBuildings',
  },
  {
    id: 39,
    imagePath: '/assets/img/oldBuildings/old-buildings-39.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 40,
    imagePath: '/assets/img/oldBuildings/old-buildings-40.jpg',
    imageAlt: 'old-builing-5',
    gallery: 'oldBuildings',
  },
  {
    id: 41,
    imagePath: '/assets/img/landscape/landscape-1.jpg',
    imageAlt: 'landscape-1',
    gallery: 'landscape',
  },
  {
    id: 42,
    imagePath: '/assets/img/landscape/landscape-2.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 43,
    imagePath: '/assets/img/landscape/landscape-3.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 44,
    imagePath: '/assets/img/landscape/landscape-4.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 45,
    imagePath: '/assets/img/landscape/landscape-5.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 46,
    imagePath: '/assets/img/landscape/landscape-6.jpg',
    imageAlt: 'landscape-6',
    gallery: 'landscape',
  },
  {
    id: 47,
    imagePath: '/assets/img/landscape/landscape-7.jpg',
    imageAlt: 'landscape-7',
    gallery: 'landscape',
  },
  {
    id: 48,
    imagePath: '/assets/img/landscape/landscape-8.jpg',
    imageAlt: 'landscape-8',
    gallery: 'landscape',
  },
  {
    id: 49,
    imagePath: '/assets/img/landscape/landscape-9.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 50,
    imagePath: '/assets/img/landscape/landscape-10.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 51,
    imagePath: '/assets/img/landscape/landscape-11.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 52,
    imagePath: '/assets/img/landscape/landscape-12.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 53,
    imagePath: '/assets/img/landscape/landscape-13.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 54,
    imagePath: '/assets/img/landscape/landscape-14.jpg',
    imageAlt: 'landscape-6',
    gallery: 'landscape',
  },
  {
    id: 55,
    imagePath: '/assets/img/landscape/landscape-15.jpg',
    imageAlt: 'landscape-7',
    gallery: 'landscape',
  },
  {
    id: 56,
    imagePath: '/assets/img/landscape/landscape-16.jpg',
    imageAlt: 'landscape-1',
    gallery: 'landscape',
  },
  {
    id: 57,
    imagePath: '/assets/img/landscape/landscape-17.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 58,
    imagePath: '/assets/img/landscape/landscape-18.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 59,
    imagePath: '/assets/img/landscape/landscape-19.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 60,
    imagePath: '/assets/img/landscape/landscape-20.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 61,
    imagePath: '/assets/img/landscape/landscape-21.jpg',
    imageAlt: 'landscape-1',
    gallery: 'landscape',
  },
  {
    id: 62,
    imagePath: '/assets/img/landscape/landscape-22.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 63,
    imagePath: '/assets/img/landscape/landscape-23.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 64,
    imagePath: '/assets/img/landscape/landscape-24.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 65,
    imagePath: '/assets/img/landscape/landscape-25.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 66,
    imagePath: '/assets/img/landscape/landscape-26.jpg',
    imageAlt: 'landscape-6',
    gallery: 'landscape',
  },
  {
    id: 67,
    imagePath: '/assets/img/landscape/landscape-27.jpg',
    imageAlt: 'landscape-7',
    gallery: 'landscape',
  },
  {
    id: 68,
    imagePath: '/assets/img/landscape/landscape-28.jpg',
    imageAlt: 'landscape-1',
    gallery: 'landscape',
  },
  {
    id: 69,
    imagePath: '/assets/img/landscape/landscape-29.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 70,
    imagePath: '/assets/img/landscape/landscape-30.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 71,
    imagePath: '/assets/img/landscape/landscape-31.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 72,
    imagePath: '/assets/img/landscape/landscape-32.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 73,
    imagePath: '/assets/img/landscape/landscape-33.jpg',
    imageAlt: 'landscape-6',
    gallery: 'landscape',
  },
  {
    id: 74,
    imagePath: '/assets/img/landscape/landscape-34.jpg',
    imageAlt: 'landscape-7',
    gallery: 'landscape',
  },
  {
    id: 75,
    imagePath: '/assets/img/landscape/landscape-35.jpg',
    imageAlt: 'landscape-1',
    gallery: 'landscape',
  },
  {
    id: 76,
    imagePath: '/assets/img/landscape/landscape-36.jpg',
    imageAlt: 'landscape-2',
    gallery: 'landscape',
  },
  {
    id: 77,
    imagePath: '/assets/img/landscape/landscape-37.jpg',
    imageAlt: 'landscape-3',
    gallery: 'landscape',
  },
  {
    id: 78,
    imagePath: '/assets/img/landscape/landscape-38.jpg',
    imageAlt: 'landscape-4',
    gallery: 'landscape',
  },
  {
    id: 79,
    imagePath: '/assets/img/landscape/landscape-39.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
  {
    id: 80,
    imagePath: '/assets/img/landscape/landscape-40.jpg',
    imageAlt: 'landscape-5',
    gallery: 'landscape',
  },
];
